version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: cid-postgres-dev
    environment:
      POSTGRES_DB: ciddb_dev
      POSTGRES_USER: ciduser
      POSTGRES_PASSWORD: cidpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database_export.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5433:5432"
    networks:
      - cid-dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ciduser -d ciddb_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Development Database Admin (Optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cid-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cidtelangana.gov.in
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    networks:
      - cid-dev-network
    depends_on:
      - postgres-dev
    restart: unless-stopped
    profiles:
      - admin

volumes:
  postgres_dev_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  cid-dev-network:
    driver: bridge